//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuild.Obfuscar.Tasks.Resources.Defaults {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcePackage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePackage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSBuild.Obfuscar.Tasks.Resources.Defaults.ResourcePackage", typeof(ResourcePackage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Obfuscator&gt;
        ///  &lt;!-- https://docs.obfuscar.com/getting-started/configuration.html --&gt;
        ///  &lt;Var name=&quot;InPath&quot; value=&quot;$$INPATH$&quot; /&gt;
        ///  &lt;Var name=&quot;OutPath&quot; value=&quot;$$OUTPATH$$&quot; /&gt;
        ///  &lt;Var name=&quot;KeepPublicApi&quot; value=&quot;true&quot; /&gt;
        ///  &lt;Var name=&quot;HidePrivateApi&quot; value=&quot;true&quot; /&gt;
        ///  &lt;Var name=&quot;HideStrings&quot; value=&quot;true&quot; /&gt;
        ///  &lt;Var name=&quot;UseUnicodeNames&quot; value=&quot;true&quot; /&gt;
        ///  &lt;Module file=&quot;$$MODULE$$&quot; /&gt;
        ///&lt;/Obfuscator&gt;.
        /// </summary>
        internal static string Obfuscar {
            get {
                return ResourceManager.GetString("Obfuscar", resourceCulture);
            }
        }
    }
}
